apiVersion: v1
kind: Namespace
metadata:
  name: saleor

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-db-pvc
  namespace: saleor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: standard

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: saleor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: saleor
        - name: POSTGRES_PASSWORD
          value: saleor
        - name: POSTGRES_DB
          value: saleor
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: saleor-db-pvc

---


apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: saleor
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP