apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
  namespace: saleor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
    spec:
      containers:
      - name: saleor-api
        image: ghcr.io/saleor/saleor:3.20
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        env:
        - name: ALLOWED_HOSTS
          value: "localhost,api,192.168.49.2,34.42.64.63,34.68.40.239"
        - name: JAEGER_AGENT_HOST
          value: "jaeger"
        - name: DASHBOARD_URL
          value: "http://localhost:9000/"
        - name: DATABASE_URL
          value: "postgres://saleor:saleor@postgres:5432/saleor"

---


apiVersion: v1
kind: Service
metadata:
  name: saleor-api
  namespace: saleor
spec:
  selector:
    app: saleor-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer